<a href="https://colab.research.google.com/github/007khun159/Python_ai_01/blob/main/Libary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Math libary
import math as m 

a = 5 
print(m.pi)
print(m.sqrt(a))
print(m.factorial(a))

3.141592653589793
2.23606797749979
120


In [5]:
r = float(input("Enter the radian"))
area = m.pi*r**2
print(area)

Enter the radian2
12.566370614359172


In [6]:
#Numpy libary

import numpy as np

x = 0

print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.pi)
print(np.e)

0.0
1.0
0.0
3.141592653589793
2.718281828459045


In [8]:
x1 = np.zeros(20)
x2 = np.ones((3,4))
print(x1)
print(x2)
0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


0

In [13]:
x  = np.array([3,4,5]  )
y = np.array([2,4,1])

print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3 4 5]
[2 4 1]
[5 8 6]
[1 0 4]
[ 6 16  5]
[1.5 1.  5. ]


In [21]:
#ทำการสร้างตัวเลข 

x = np.arange(0,10,0.1)
print(x)
print('-'*90)
print(3*x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
------------------------------------------------------------------------------------------
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7 15.  15.3 15.6 15.9 16.2 16.5
 16.8 17.1 17.4 17.7 18.  18.3 18.6 18.9 19.2 19.5 19.8 20.1 20.4 20.7
 21.  21.3 21.6 21.9 22.2 22.5 22.8 23.1 23.4 23.7 24.  24.3 24.6 24.9
 25.2 25.5 25.8 26.1 26.4 26.7 27.  27.3 27.6 27.9 28.2 28.5 28.8 29.1
 29.4

In [25]:
x = np.arange(0,2*np.pi,np.pi/6)
print(x)
print('-'*60)
print(np.sin(x))

[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653]
------------------------------------------------------------
[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01]
