<a href="https://colab.research.google.com/github/007khun159/Python_ai_01/blob/main/Libary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Math libary
import math as m 

a = 5 
print(m.pi)
print(m.sqrt(a))
print(m.factorial(a))

3.141592653589793
2.23606797749979
120


In [2]:
r = float(input("Enter the radian"))
area = m.pi*r**2
print(area)

Enter the radian200
125663.70614359173


In [7]:
#Numpy libary

import numpy as np

x = 0

print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.pi)
print(np.e)

0.0
1.0
0.0
3.141592653589793
2.718281828459045


In [12]:
x1 = np.zeros(20)
x2 = np.ones((3,4))
print(x1)+456
print(x2)
0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
